### Site metadata ###

site_name: MkDocs Quickstart
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://michaelcurrin.github.io/mkdocs-quickstart/

repo_url: https://github.com/MichaelCurrin/mkdocs-quickstart
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - Tutorial:
      - Getting Started: GS/Installation.md
      - Configuration: GS/configuration.md
      - Usage: tutorial/usage.md
  - Generate Population:
      - Run Pipeline : 
        - Set Data Sources: GS/run-pipeline-1.md
        - Preprocess Data: GS/run-pipeline-2.md
        - IPU: GS/run-pipeline-3.md
        - Add Features to the Base Population: GS/run-pipeline-4.md
        - Results : GS/run-pipeline-5.md
        - Adding Optional Attributes to the Base Population: GS/run-pipeline-6.md
  - Files:
      - Docs:
        - synthpop.py : GS/synthpop.md
        - IPU.py : GS/IPU.md
        - age-height-weight.py : GS/AHW.md
        - HlatHlongaddition.py : GS/latlong.md
        - places.py : GS/Places.md
        - population_density_sampler.py : GS/PDS.md
      
      